export type * from './types'
export { profile } from './profile'
export { projects, featuredProjects, projectTags, projectsPage } from './projects'
export { experience } from './experience'
export { education } from './education'
export { skills } from './skills'
export { contactPage, type ContactPageContent } from './contact'
export { aboutPage } from './about'
export { formatYearMonth, formatDateRange, PRESENT_LABEL } from './format'
export { home } from './home'
export { resumePage, type ResumePageContent } from './resume'
